USE BeautySalo

CREATE TABLE ServiceBS
(
	ID INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(100) NOT NULL,
	SurName NVARCHAR(200) NOT NULL,
	DirectionID INT NOT NULL,
	ExhibitNumber INT NOT NULL,
	FOREIGN KEY (DirectionID) REFERENCES Category(ID)
)

CREATE TABLE Category
(
	ID INT PRIMARY KEY IDENTITY,
	NameC NVARCHAR(150) NOT NULL,
	DescriptionC NVARCHAR(250) NOT NULL
)